steps:
  - name: 'mirror.gcr.io/library/python'
    env:
      - SD2TEAMS_MODE=Test
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          pip install -r requirements.txt && python -m unittest
    dir: 'app'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'sd_to_teams', '--trigger-http', '--runtime', 'python37', '--entry-point',
           'send_to_teams', '--allow-unauthenticated', '--memory', '128',
           '--set-env-vars', 'MS_TEAMS_WEBHOOK=$$MS_TEAMS_WEBHOOK,SD2TEAMS_MODE=Prod']
    dir: 'app'
    secretEnv:
      - MS_TEAMS_WEBHOOK

secrets:
  - kmsKeyName: projects/toryburch-services-test/locations/us-central1/keyRings/sd2teams-secrets/cryptoKeys/sd2teams-secrets
    secretEnv:
      MS_TEAMS_WEBHOOK: CiQARxmVUgFKnJzsJbutDU4PX8GondEvB3+2HVu0Dq+co2ZsBnYS7AEAoFWrjHPJMHOWXNx2uDa8cSiUw+QgXdTvxNb09sq6zMEIAxBEW62WeS0M2BR3kxrf4uHeDka8S1AM7ljwvBU3cneYUYCwR8WvZWq1S3qTa8wvFBMR9dEdZ+xGm7KecFHyhmMW2ddn9RJ/AuazIDOfNunr+/RcFuylJ+8W1mj7pD/wDpDealGTgegPy2HXWmbUzihrLKCiqKaRZtZV7clY8DMlD7bBOaVJ3aBM5b+7pQ7pMKfcYSqEP4CzU2hC5Xz5pNyxx6qbU0jORoEIz0B+3+aqDrDlVWnrylkeHUm7PgyGZa4g/60OcyH/Ew==
  